wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709558851.777437
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 13
      - 14
      - 23
      - 58
      4: 3.10.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
id:
  desc: null
  value: ftjob-L36vT4dDnkWzL9GckJ0SssVm
created_at:
  desc: null
  value: '2024-03-04 14:19:02'
error:
  desc: null
  value: Error(code=None, message=None, param=None, error=None)
fine_tuned_model:
  desc: null
  value: ft:gpt-3.5-turbo-0125:kifabrik-mirmi:kios-ut-gen-v3:8z2ZAg2T
finished_at:
  desc: null
  value: '2024-03-04 14:22:43'
model:
  desc: null
  value: ft:gpt-3.5-turbo-0125:kifabrik-mirmi:kios-ut-gen-v2:8z2KbPsr
object:
  desc: null
  value: fine_tuning.job
organization_id:
  desc: null
  value: org-ygWwisor3PBcF2dPNRDTzzgd
result_files:
  desc: null
  value: file-BZkZkwLqXcoQNXF0OkJpwEsr
status:
  desc: null
  value: succeeded
trained_tokens:
  desc: null
  value: 166931
training_file:
  desc: null
  value: file-D8aBgTaXbp3g42RcV2bTiKDK
validation_file:
  desc: null
  value: null
user_provided_suffix:
  desc: null
  value: kios_ut_gen_v3
hyperparameters:
  desc: null
  value:
    n_epochs: 1
    batch_size: 3
    learning_rate_multiplier: 0.5
n_train:
  desc: null
  value: 60
