wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709557987.155776
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 13
      - 14
      - 23
      - 37
      - 58
      4: 3.10.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
id:
  desc: null
  value: ftjob-AncbMuC4XGCe9OOk4zjjAz5g
created_at:
  desc: null
  value: '2024-03-03 16:12:46'
error:
  desc: null
  value: Error(code=None, message=None, param=None, error=None)
fine_tuned_model:
  desc: null
  value: ft:gpt-3.5-turbo-0125:kifabrik-mirmi:kios-ut-gen-v1:8yhtwL2A
finished_at:
  desc: null
  value: '2024-03-03 16:18:48'
model:
  desc: null
  value: gpt-3.5-turbo-0125
object:
  desc: null
  value: fine_tuning.job
organization_id:
  desc: null
  value: org-ygWwisor3PBcF2dPNRDTzzgd
result_files:
  desc: null
  value: file-5b2b35XQYTgpFUQglt1jjtIY
status:
  desc: null
  value: succeeded
trained_tokens:
  desc: null
  value: 500793
training_file:
  desc: null
  value: file-D8aBgTaXbp3g42RcV2bTiKDK
validation_file:
  desc: null
  value: null
user_provided_suffix:
  desc: null
  value: kios_ut_gen_v1
hyperparameters:
  desc: null
  value:
    n_epochs: 3
    batch_size: 6
    learning_rate_multiplier: 0.1
n_train:
  desc: null
  value: 60
