wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709558093.756392
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 13
      - 14
      - 23
      - 58
      4: 3.10.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
id:
  desc: null
  value: ftjob-kdM1O1dj6DYbYcykXXKyikqt
created_at:
  desc: null
  value: '2024-03-04 14:03:20'
error:
  desc: null
  value: Error(code=None, message=None, param=None, error=None)
fine_tuned_model:
  desc: null
  value: ft:gpt-3.5-turbo-0125:kifabrik-mirmi:kios-ut-gen-v2:8z2KbPsr
finished_at:
  desc: null
  value: '2024-03-04 14:07:40'
model:
  desc: null
  value: ft:gpt-3.5-turbo-0125:kifabrik-mirmi:kios-ut-gen-v1:8yhtwL2A
object:
  desc: null
  value: fine_tuning.job
organization_id:
  desc: null
  value: org-ygWwisor3PBcF2dPNRDTzzgd
result_files:
  desc: null
  value: file-tZbs1XUN3ch21P5hGoXSvyCX
status:
  desc: null
  value: succeeded
trained_tokens:
  desc: null
  value: 333862
training_file:
  desc: null
  value: file-D8aBgTaXbp3g42RcV2bTiKDK
validation_file:
  desc: null
  value: null
user_provided_suffix:
  desc: null
  value: kios_ut_gen_v2
hyperparameters:
  desc: null
  value:
    n_epochs: 2
    batch_size: 6
    learning_rate_multiplier: 0.25
n_train:
  desc: null
  value: 60
